# Run it: docker-compose up -d
# Run only one service: docker-compose up -d stolovaya51-react-dev

version: '3'
services:
  # You can rename this service special for docker-hub like: ydubovitsky/stolovaya51 
  stolovaya51-react-dev:
    container_name: stolovaya51-react-dev
    build:
      dockerfile: ./docker/dev/Dockerfile
    environment:
      # Prefix REACT_APP has a matter!
      REACT_APP_BACKEND_URL: http://stolovaya51-spring:8085
    ports:
     - "80:3000"

  stolovaya51-react-production:
    container_name: stolovaya51-react-production
    build: 
      dockerfile: ./docker/production/Dockerfile
    environment:
      # Prefix REACT_APP has a matter!
      REACT_APP_BACKEND_URL: http://stolovaya51-spring:8085
    ports:
      - "80:80"