# How to use it?
# docker compose -f docker-compose-prod.yml up

version: '3'
services:
  # You can rename this service special for docker-hub like: ydubovitsky/stolovaya51
  stolovaya51-spring:
    build:
      context: ./stolovaya51-spring
      dockerfile: ./docker/production/Dockerfile
    environment:
      PROFILE_ACTIVE: ${PROFILE_ACTIVE}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_URL: jdbc:postgresql://stolovaya51-db:5432/postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DDL_AUTO: ${POSTGRES_DDL_AUTO}
    depends_on:
      - stolovaya51-db
    networks:
      - stolovaya51

  stolovaya51-react:
    build:
      dockerfile: ./docker/production/Dockerfile
      args:
        # Change me!
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    networks:
     - stolovaya51

  stolovaya51-db:
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - stolovaya51-db:/data/postgres
    networks:
      - stolovaya51
    restart: unless-stopped

networks:
  stolovaya51:
    driver: bridge

volumes:
  stolovaya51-db: